# Copyright 2026 Samuel Talkington and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

using Documenter
using PowerModelsDiff

site_build = get(ENV, "SITE_BUILD", "false") == "true"

format_opts = if site_build
    # Build for personal website: pretty URLs, canonical link, no edit links
    Documenter.HTML(
        prettyurls = true,
        canonical = "https://samueltalkington.com/research/pmdiff/",
        edit_link = nothing,
    )
else
    # Default: local or CI build
    Documenter.HTML(
        prettyurls = get(ENV, "CI", nothing) == "true",
    )
end

makedocs(
    sitename = "PowerModelsDiff.jl",
    modules = [PowerModelsDiff],
    format = format_opts,
    pages = [
        "Home" => "index.md",
        "Getting Started" => "getting-started.md",
        "Sensitivity API" => "sensitivity-api.md",
        "Mathematical Background" => "math.md",
        "Advanced Topics" => "advanced.md",
        "API Reference" => "api.md",
    ],
    warnonly = [:missing_docs],
)

if site_build
    # Stub siteinfo.js — normally generated by deploydocs(), which we skip.
    # Prevents a 404 when Documenter's JS requests it.
    write(joinpath(@__DIR__, "build", "siteinfo.js"),
        """var DOCUMENTER_CURRENT_VERSION = "dev";""")
else
    deploydocs(
        repo = "github.com/grid-opt-alg-lab/PowerModelsDiff.jl.git",
        devbranch = "main",
    )
end
