# Copyright 2026 Samuel Talkington and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

using Changelog
using Documenter
using PowerDiff

site_build = get(ENV, "SITE_BUILD", "false") == "true"

format_opts = if site_build
    # Build for personal website: pretty URLs, canonical link, no edit links
    Documenter.HTML(
        prettyurls = true,
        canonical = "https://samueltalkington.com/research/powerdiff/",
        edit_link = nothing,
    )
else
    # Default: local or CI build
    Documenter.HTML(
        prettyurls = get(ENV, "CI", nothing) == "true",
    )
end

# Render CHANGELOG.md into a docs page, turning issue, pull request and version
# references into links. The output is generated on every build and is not
# tracked; CHANGELOG.md at the repository root remains the single source.
Changelog.generate(
    Changelog.Documenter(),
    joinpath(@__DIR__, "..", "CHANGELOG.md"),
    joinpath(@__DIR__, "src", "changelog.md");
    repo = "grid-opt-alg-lab/PowerDiff.jl",
)

makedocs(
    sitename = "PowerDiff.jl",
    modules = [PowerDiff],
    checkdocs = :exports,  # only verify exported symbols have @docs entries
    format = format_opts,
    pages = [
        "Home" => "index.md",
        "Getting Started" => "getting-started.md",
        "Sensitivity API" => "sensitivity-api.md",
        "Mathematical Details" => [
            "DC Power Flow" => "math/dc-power-flow.md",
            "DC Optimal Power Flow" => "math/dc-opf.md",
            "AC Power Flow" => "math/ac-power-flow.md",
            "AC Optimal Power Flow" => "math/ac-opf.md",
        ],
        "PowerIO Integration" => "powerio-integration.md",
        "Advanced Topics" => "advanced.md",
        "API Reference" => "api.md",
        "Changelog" => "changelog.md",
    ],
)

if site_build
    # Stub siteinfo.js — normally generated by deploydocs(), which we skip.
    # Prevents a 404 when Documenter's JS requests it.
    write(joinpath(@__DIR__, "build", "siteinfo.js"),
        """var DOCUMENTER_CURRENT_VERSION = "dev";""")
else
    deploydocs(
        repo = "github.com/grid-opt-alg-lab/PowerDiff.jl.git",
        devbranch = "main",
    )
end
