using Documenter
using PowerModelsDiff

site_build = get(ENV, "SITE_BUILD", "false") == "true"

format_opts = if site_build
    # Build for personal website: pretty URLs, canonical link, no edit links
    Documenter.HTML(
        prettyurls = true,
        canonical = "https://samueltalkington.com/research/pmdiff/",
        edit_link = nothing,
    )
else
    # Default: local or CI build
    Documenter.HTML(
        prettyurls = get(ENV, "CI", nothing) == "true",
    )
end

makedocs(
    sitename = "PowerModelsDiff.jl",
    modules = [PowerModelsDiff],
    format = format_opts,
    pages = [
        "Home" => "index.md",
        "Getting Started" => "getting-started.md",
        "Sensitivity API" => "sensitivity-api.md",
        "Mathematical Background" => "math.md",
        "Advanced Topics" => "advanced.md",
        "API Reference" => "api.md",
    ],
    warnonly = [:missing_docs],
)

if site_build
    # Stub siteinfo.js — normally generated by deploydocs(), which we skip.
    # Prevents a 404 when Documenter's JS requests it.
    write(joinpath(@__DIR__, "build", "siteinfo.js"),
        """var DOCUMENTER_CURRENT_VERSION = "dev";""")
else
    deploydocs(
        repo = "github.com/grid-opt-alg-lab/PowerModelsDiff.jl.git",
        devbranch = "main",
    )
end
